namespace Infrastructure.Google;

/// <summary>
/// Result of a proactive Google Chat API message post.
/// </summary>
/// <param name="MessageName">
/// Full resource name of the created message, e.g. "spaces/xxx/messages/yyy".
/// Stored on the ticket as <c>MessageName</c>.
/// </param>
/// <param name="ThreadName">
/// Full resource name of the thread, e.g. "spaces/xxx/threads/zzz".
/// Stored on the ticket as <c>ThreadName</c> and used for all subsequent replies.
/// </param>
public sealed record ChatPostResult(string MessageName, string ThreadName);

/// <summary>
/// Proactive Google Chat API messaging — used by the Worker to send notifications
/// without an incoming webhook trigger.
/// </summary>
public interface IGoogleChatApiService
{
    /// <summary>
    /// Posts a notification card to the configured Chat space announcing a new bug-report file.
    /// The card contains only the filename and a one-sentence description — no action buttons.
    /// The <b>Analyze</b> button lives in the file-content card posted separately in the thread.
    /// </summary>
    /// <param name="spaceName">Target space, e.g. "spaces/XXXXXXXXX".</param>
    /// <param name="fileName">Display name of the Drive file.</param>
    /// <param name="description">One-sentence description generated by the LLM.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>Names of the created message and its thread.</returns>
    Task<ChatPostResult> PostNotificationCardAsync(
        string spaceName, string fileName, string description,
        CancellationToken ct = default);

    /// <summary>
    /// Posts a card inside an existing thread containing the full file content
    /// and an <b>Analyze</b> button at the bottom.
    /// Clicking the button sends a <c>CARD_CLICKED</c> event that
    /// <c>ActionController</c> handles; <c>UPDATE_MESSAGE</c> will update only
    /// this thread card — the main notification card is never touched.
    /// </summary>
    /// <param name="spaceName">Target space, e.g. "spaces/XXXXXXXXX".</param>
    /// <param name="threadName">Thread to reply to, e.g. "spaces/xxx/threads/zzz".</param>
    /// <param name="fileName">Display name of the Drive file (shown inside the card).</param>
    /// <param name="content">Extracted text content of the file (may be empty for images).</param>
    /// <param name="ticketId">Ticket GUID embedded in the Analyze button action parameter.</param>
    /// <param name="ct">Cancellation token.</param>
    Task PostFileContentCardAsync(
        string spaceName, string threadName,
        string fileName, string content, Guid ticketId,
        CancellationToken ct = default);

    /// <summary>
    /// Posts a plain-text reply inside an existing thread.
    /// Used for status updates, analysis results, and branch notifications.
    /// </summary>
    /// <param name="spaceName">Target space, e.g. "spaces/XXXXXXXXX".</param>
    /// <param name="threadName">Thread to reply to, e.g. "spaces/xxx/threads/zzz".</param>
    /// <param name="text">Message body (Google Chat markdown supported).</param>
    /// <param name="ct">Cancellation token.</param>
    Task PostThreadReplyAsync(
        string spaceName, string threadName, string text,
        CancellationToken ct = default);

    /// <summary>
    /// Posts an arbitrary message body as a thread reply.
    /// Use this to post a card (e.g. a serialisable <c>CardResponse</c>) after
    /// an asynchronous operation completes, so the thread always shows the
    /// current ticket state with the correct action buttons.
    /// </summary>
    /// <param name="spaceName">Target space, e.g. "spaces/XXXXXXXXX".</param>
    /// <param name="threadName">Thread to reply to, e.g. "spaces/xxx/threads/zzz".</param>
    /// <param name="body">
    /// Any serialisable object. Pass a <c>CardResponse</c> instance to post a card,
    /// or an anonymous object with a <c>text</c> property for plain text.
    /// </param>
    /// <param name="ct">Cancellation token.</param>
    Task PostThreadMessageAsync(
        string spaceName, string threadName, object body,
        CancellationToken ct = default);
}
